In [1]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from nltk.corpus import stopwords
import matplotlib.pylab as pylab
import matplotlib.pyplot as plt
from pandas import get_dummies
import matplotlib as mpl
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
import warnings
import sklearn
import string
import scipy
import numpy
import nltk
import json
import sys
import csv
import os

In [2]:
#import dataset
funding_rounds = pd.read_csv("/Users/lucyhyde/Desktop/Practicum_Data/funding_rounds.csv")

In [3]:
type(funding_rounds)

pandas.core.frame.DataFrame

In [4]:
#shape
print(funding_rounds.shape)

(102628, 10)

In [5]:
print(funding_rounds.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102628 entries, 0 to 102627
Data columns (total 10 columns):
org_permalink                            102628 non-null object
funding_round_permalink                  102628 non-null object
round_number                             102628 non-null int64
funding_round_announced_on               102628 non-null object
days_btw_rounds                          50160 non-null float64
funding_round_type                       102628 non-null object
funding_round_series                     26847 non-null object
clean_round                              97579 non-null object
funding_round_money_raised_usd           80630 non-null float64
funding_round_pre_money_valuation_usd    3490 non-null float64
dtypes: float64(3), int64(1), object(6)
memory usage: 7.8+ MB
None

In [6]:
funding_rounds.head(10)

,org_permalink,funding_round_permalink,round_number,funding_round_announced_on,days_btw_rounds,funding_round_type,funding_round_series,clean_round,funding_round_money_raised_usd,funding_round_pre_money_valuation_usd
0,004-technologies,1278dd4e6a37fa4b7d7e06c21b3c1830,1,7/24/14,NaN,venture,NaN,Unknown,NaN,NaN
1,0chain,8643015e6d6e45ab8508e658bf0e18f7,1,2/7/18,NaN,initial_coin_offering,NaN,ICO,39000000.0,NaN
2,0chain,009ec1dbf7604d37b307be8d7202c442,2,2/8/18,1.0,seed,NaN,Seed,NaN,NaN
3,0x-project,ea1d53d8a2e2110bd44f137a07b0c149,1,6/29/17,NaN,initial_coin_offering,NaN,ICO,24000000.0,NaN
4,0x-project,79ebc1b84e4e47daa5c0f43be784fe6c,2,8/15/17,47.0,seed,NaN,Seed,NaN,NaN
5,0x-project,af09dbc1c670427984f44515bdf4ef62,3,10/1/17,47.0,venture,NaN,Seed,NaN,NaN
6,0x-project,cc83f2013ecb4d2ab565d0693446c381,4,10/1/17,0.0,undisclosed,NaN,Seed,NaN,NaN
7,1,e82464f22241715dd1a6c77241055ed1,1,7/20/11,NaN,seed,NaN,Seed,1000050.0,NaN
8,1,5de6d8828aef7d925d97918d15727670,2,2/5/13,566.0,venture,NaN,Seed,NaN,NaN
9,1,03b975068632eba5bfdb937ec8c07a68,3,2/5/14,365.0,seed,NaN,Seed,150000.0,NaN

In [7]:
funding_rounds.tail(10)

,org_permalink,funding_round_permalink,round_number,funding_round_announced_on,days_btw_rounds,funding_round_type,funding_round_series,clean_round,funding_round_money_raised_usd,funding_round_pre_money_valuation_usd
102618,zyrl-ecdd,ae5ef5b3383b49aaa644f9fa9d95b8d6,1,1/17/17,NaN,undisclosed,NaN,Seed,100000.0,NaN
102619,zyrl-ecdd,67f1dafc3fb04d7aac501c5eefa3bbd1,2,7/1/17,165.0,convertible_note,NaN,Seed,200000.0,2000000.0
102620,zyrl-ecdd,ca4de8e696f14b0389d73fcfc0f9e035,3,4/2/18,275.0,seed,NaN,Seed,250000.0,NaN
102621,zyston,3589a164533898b3ab14d8e7edc796b9,1,6/28/16,NaN,venture,A,A,3700000.0,NaN
102622,zyston,5da00dbb5d71919b77698ec513c9ffad,2,5/10/17,316.0,venture,NaN,B,2200000.0,NaN
102623,zystor,7ea37c0ff4132b084832039a9380d34e,1,12/16/04,NaN,venture,A,A,8500000.0,NaN
102624,zy-therapeutics,2f15bae5c5749c44b8b2edca9ca30188,1,6/14/16,NaN,venture,NaN,A,6000000.0,NaN
102625,zyudly-labs,b945f9835425a2ac808bbab2d5dcc1db,1,5/11/17,NaN,seed,NaN,Seed,NaN,NaN
102626,zz-biotech,182f7b627217f117c7fdd0addee9bf6c,1,3/13/14,NaN,seed,NaN,Seed,1000000.0,NaN
102627,zz-biotech,5aeb3087f3aaa56eff24f8275c38ca6d,2,1/1/15,294.0,venture,NaN,A,6930000.0,NaN

In [8]:
funding_rounds.describe()

,round_number,days_btw_rounds,funding_round_money_raised_usd,funding_round_pre_money_valuation_usd
count,102628.000000,50160.000000,8.063000e+04,3.490000e+03
mean,2.127188,474.988975,9.064468e+06,3.558772e+08
std,1.635953,458.756568,4.742619e+07,2.790302e+09
min,1.000000,0.000000,0.000000e+00,5.000000e+04
25%,1.000000,190.000000,4.300040e+05,2.000000e+06
50%,1.000000,365.000000,2.000000e+06,5.000000e+06
75%,3.000000,612.000000,7.300000e+06,2.437500e+07
max,13.000000,6665.000000,7.700000e+09,7.150000e+10

In [9]:
funding_rounds.nlargest(10, 'funding_round_money_raised_usd')

,org_permalink,funding_round_permalink,round_number,funding_round_announced_on,days_btw_rounds,funding_round_type,funding_round_series,clean_round,funding_round_money_raised_usd,funding_round_pre_money_valuation_usd
93392,uber,fc34230ad1da1702997983a75b8f1d7f,8,12/28/17,0.0,secondary_market,NaN,Post IPO,7.700000e+09,4.030000e+10
93388,uber,3561e0558d4fa07f0dc27a9d380fd0ae,4,6/1/16,110.0,venture,G,Post D,3.500000e+09,5.900000e+10
42522,infor,d39e11a9c575b22749a538878043a9bd,3,11/16/16,1686.0,private_equity,NaN,PE,2.500000e+09,7.500000e+09
15425,carestream-health,7850c5af2d7229dbef8246a2d8e8cdea,1,6/12/13,NaN,debt_financing,NaN,Debt,2.400000e+09,NaN
31249,faraday-future,08d8ce45d4e04c39bc53ced70b5ca666,2,12/20/17,134.0,corporate_round,NaN,Corporate,2.000000e+09,2.450000e+09
101646,zebra-technologies,cd35f92a07d13fc19fa196b6b72aecab,2,9/16/14,2329.0,post_ipo_debt,NaN,Post IPO,2.000000e+09,NaN
56992,mpt-operating-partnership,8b9e29ed9b7644d4459347c2bcc105c2,1,2/2/17,NaN,debt_financing,NaN,Debt,1.700000e+09,NaN
3132,airbnb,8ab0470b7e24485f60b57ad0378ba13a,5,6/28/15,438.0,venture,E,Post D,1.500000e+09,2.400000e+10
95342,venari-resources,5947e073d9d3bbdbd9714f38258fbfae,1,7/23/14,NaN,private_equity,NaN,PE,1.498515e+09,NaN
26325,dupage-medical-group,538a14274a17e33e27cad6567c792d59,2,8/16/17,588.0,private_equity,NaN,PE,1.450000e+09,NaN

In [11]:
funding_rounds.nlargest(10, 'funding_round_pre_money_valuation_usd')

,org_permalink,funding_round_permalink,round_number,funding_round_announced_on,days_btw_rounds,funding_round_type,funding_round_series,clean_round,funding_round_money_raised_usd,funding_round_pre_money_valuation_usd
93394,uber,be7136e2486e4ad2a909b7da62e6c029,10,8/27/18,96.0,corporate_round,NaN,Corporate,5.000000e+08,7.150000e+10
93391,uber,ca0a4dde120d4dec9520cf7c48ed17ae,7,12/28/17,253.0,venture,NaN,NaN,1.250000e+09,6.880000e+10
93388,uber,3561e0558d4fa07f0dc27a9d380fd0ae,4,6/1/16,110.0,venture,G,Post D,3.500000e+09,5.900000e+10
93393,uber,6dae3de6bded4eaeaf37ad588ab0eee9,9,5/23/18,146.0,secondary_market,NaN,Post IPO,6.000000e+08,5.600000e+10
93385,uber,c738765257ab10e721f1a02d5af54681,1,7/31/15,NaN,venture,F,Post D,1.000000e+09,5.000000e+10
93392,uber,fc34230ad1da1702997983a75b8f1d7f,8,12/28/17,0.0,secondary_market,NaN,Post IPO,7.700000e+09,4.030000e+10
3137,airbnb,e707522703416c958a9256485dc239a3,10,3/9/17,143.0,venture,F,Post D,4.480000e+08,3.000000e+10
3135,airbnb,b7e02f8303ee22acff0db6b477a781be,8,9/22/16,98.0,venture,F,Post D,5.554621e+08,2.940000e+10
3133,airbnb,47de508203de515a569130787dc50dbe,6,11/20/15,145.0,venture,E,Post D,1.000000e+08,2.450000e+10
3132,airbnb,8ab0470b7e24485f60b57ad0378ba13a,5,6/28/15,438.0,venture,E,Post D,1.500000e+09,2.400000e+10

In [10]:
funding_rounds.isnull().sum()

org_permalink                                0
funding_round_permalink                      0
round_number                                 0
funding_round_announced_on                   0
days_btw_rounds                          52468
funding_round_type                           0
funding_round_series                     75781
clean_round                               5049
funding_round_money_raised_usd           21998
funding_round_pre_money_valuation_usd    99138
dtype: int64

In [12]:
funding_rounds.columns

Index(['org_permalink', 'funding_round_permalink', 'round_number',
       'funding_round_announced_on', 'days_btw_rounds', 'funding_round_type',
       'funding_round_series', 'clean_round', 'funding_round_money_raised_usd',
       'funding_round_pre_money_valuation_usd'],
      dtype='object')